name: Android Debug Build & Email

on:
  workflow_dispatch:

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Check if APK exists
        run: ls -lh app/build/outputs/apk/debug/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Send APK to tester via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CI] Android Debug APK"
          body: |
            APK mới đã được build thành công.
            Tải file APK tại tab Artifacts trong workflow run:
            https://github.com/AlexVocao/CalculateTip/actions/runs/${{ github.run_id }}
          to: caohoavo22@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: app/build/outputs/apk/debug/app-debug.apk
