name: Android Release Build & Email (Manual)

on:
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Decode keystore from base64
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
              echo "Decoding keystore..."
              echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks
              echo "Keystore decoded successfully."
          else
              echo "No keystore found. Skipping decoding step."
          fi

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEY_ALIAS }}

      - name: Install build-tools 34.0.0
        run: sdkmanager "build-tools;34.0.0"

      - name: Align APK
        run: |
            @ANDROID_HOME@/build-tools/34.0.0/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release.apk

      - name: Check if APK exists
        run: ls -lh app/build/outputs/apk/release/

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Send APK to tester via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "[CI] Android Release APK"
          body: |
            APK mới đã được build thành công.
            Tải file APK tại tab Artifacts trong workflow run:
            https://github.com/AlexVocao/CalculateTip/actions/runs/${{ github.run_id }}
          to: caohoavo22@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: app/build/outputs/apk/release/app-release.apk